version: 0.2
env:
    variables:
        REGION: ap-northeast-2
        ECR_REPO: httpd
phases:
    install:
        runtime-versions:
            docker: 19
    pre_build:
        commands:
            - ACCOUNT=$(aws sts get-caller-identity --query 'Account' --output text)
            - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 611683015416.dkr.ecr.ap-northeast-2.amazonaws.com
            - ECR_REPO_URI=${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO}
    build:
        commands:
            - docker build -t ${ECR_REPO_URI}:v${CODEBUILD_BUILD_NUMBER} .
    post_build:
        commands:
            - docker push ${ECR_REPO_URI}:v${CODEBUILD_BUILD_NUMBER}
            - printf '[{"name":"httpd", "imageUri":"%s"}]' ${ECR_REPO_URI}:v${CODEBUILD_BUILD_NUMBER} > imageDefinition.json
artifacts:
    files:
        - imageDefinition.json
